// args: --run

def main(){
	def foo(x:!𝔹){ return 2; }
	return (foo coerce !ℚ!→!𝔹)(1/2); /// error // TODO: catch at runtime?
}
